version: '3.8'
services:
    postgres:
        build:
          context: .
          dockerfile: Dockerfile.Postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
          - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    gistdrive:
        image: gistdrive:1.0
        environment:
            - PIPEDRIVE_TOKEN=<your_token>
            - PIPEDRIVE_ORG=<your_org>
            - POSTGRES_CONNECTION_STRING=<connection>
        ports:
            - 8080:8080
        command: ["bash","./wait-for-it/wait-for-it.sh", "postgres:5432", "--", "go",  "run", "main.go"]
          
