version: '3.8'
services:
    postgres:
        build:
          context: .
          dockerfile: Dockerfile.Postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
          - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
