apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: gistdrive
  name: gistdrive
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gistdrive
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: gistdrive
    spec:
      containers:
        - args:
            - bash
            - ./wait-for-it/wait-for-it.sh
            - postgres:5432
            - --
            - go
            - run
            - main.go
          env:
            - name: PIPEDRIVE_ORG
              value: <org>
            - name: PIPEDRIVE_TOKEN
              value: <token>
            - name: POSTGRES_CONNECTION_STRING
              value: <connection>
          image: <image_repo>
          name: gistdrive
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
